### ISSUE TITLE
Write end to end tests

### ISSUE THREAD

**Issue by ultimatecoder** [ultimatecoder/javascript_port_scanner#3]
## Description

Add end to end tests for the application.

## Sub-tasks

- [ ] Scenarios
  - [x] ~~I am a User. I should be able to identify name of the tool and its purpose.~~ PR : #7 
  - [x] ~~I am a User. Assume there are no services running between ports 8050 to 8070 then scan for those ports should not detect any.~~ PR: #8 
  - [x] ~~I am a User. Assume there is a MongoDB running on 27017 port and Next Cloud service running on port 8080, then scan between 27010 and 27030 should only detect MongoDB service.~~ PR: #15 
  - [ ] I am a User. Assume there is a MongoDB service running on 27017 port and Next Cloud service running on port 8084, then scan between 8050 and 9000 should only detect NextCloud service on port 8084.
  - [x] ~~I am a User. When I start scan, I should be able to stop the running scan. ~~ #22 
- [x] ~~Write end to end tests for written scenarios in Python Selenium.~~
- [x] ~~Configure Firefox to run this end to end tests.~~
- [ ] Wrap in to Docker compose
